### ISSUE TITLE
[bug] Unable to download artifact(s): Unable to download and extract artifact: Request timeout

### ISSUE THREAD

**Issue by mathbunnyru** [actions/download-artifact#249]
### What happened?

My GitHub workflow tried to download an artifact and got the following error:

```
Unable to download artifact(s): Unable to download and extract artifact: Request timeout: /actions-results/48835bcc-3d9d-48c1-9b25-e61724c412e6/workflow-job-run-133fda40-ba8c-5571-226b-e94c9a723dbe/artifacts/scipy-notebook-x86_64.zip?se=2023-12-14T22%3A41%3A57Z&sig=kIu7CPVgJ9myrpzJC9NS%2FLVc8z8fcQtdDXC0sDa5DVc%3D&sp=r&spr=https&sr=b&st=2023-12-14T22%3A31%3A57Z&sv=2021-12-02
```

The link is here:
https://github.com/jupyter/docker-stacks/actions/runs/7214568077

### What did you expect to happen?

Successful run

### How can we reproduce it?

Possibly fork `jupyter/docker-stacks` and run the `docker.yml` workflow

### Anything else we need to know?

I tried to restart the build a few times - seems to work sometimes.
The runner which downloads the artifact is a GitHub-hosted runner.

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by mathbunnyru** [comment]
This only happened when I switched to v4 a few hours ago.

**Comment by AurevoirXavier** [comment]
Same here.

**Comment by IvanGithub-Professional** [comment]
@mathbunnyru I had a very similar Issue created earlier about an artifact not being found. This is a little different because you are receiving a "**Request Timeout**" but maybe my solution will fix yours. The issue is not being consistent with your Upload & Download versions. I was uploading with version 3 and downloading with version 4. Mine was not considered a bug because it is documented as expected.

My soultion was this
Solution: Be consistent with the versions with your **Upload** & **Download** such as `action/upload-artifact@v4` and `actions/download-artifact@v4`

**Comment by mathbunnyru** [comment]
> @mathbunnyru I had a very similar Issue created earlier about an artifact not being found. This is a little different because you are receiving a "**Request Timeout**" but maybe my solution will fix yours. The issue is not being consistent with your Upload & Download versions. I was uploading with version 3 and downloading with version 4. Mine was not considered a bug because it is documented as expected.
> 
> 
> 
> My soultion was this
> 
> Solution: Be consistent with the versions with your **Upload** & **Download** such as `action/upload-artifact@v4` and `actions/download-artifact@v4`

Thank you. Unfortunately, I already use v4 in all uploads and downloads.

**Comment by submarines-and** [comment]
Happens to us intermittently as well. Both actions are v4

**Comment by Santas** [comment]
After upgrading to v4 we saw similar issue
```
Error: Unable to download artifact(s): Unable to download and extract artifact: Unexpected HTTP response from blob storage: 503 The server is busy.
```

**Comment by jamezp** [comment]
Just another "I'm seeing this too" https://github.com/resteasy/resteasy-microprofile/actions/runs/7224411814. The artifact is definitely there.

**Comment by cmeister2** [comment]
Ditto, after upgrading curl/curl-fuzzer from v3 to v4.

**Comment by JasonGross** [comment]
Another example: https://github.com/mit-plv/fiat-crypto/actions/runs/7226837418/job/19695450596?pr=1786#step:6:20 both upload and download are v4.  Is the new backend very unstable or something?

**Comment by davidlj95** [comment]
Same here after upgrading to v4. Recent example: https://github.com/davidlj95/ngx/actions/runs/7242522151/job/19728111845

**Comment by baywet** [comment]
Facing the same issue here.

After digging into this a little bit, it seems the code is actually in another repo

https://github.com/actions/download-artifact/blob/1bd0606e08fcaa4c28afc1fc7d45830ab5482dac/src/download-artifact.ts#L4

https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/artifact/src/internal/download/download-artifact.ts#L101

https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/artifact/src/internal/download/download-artifact.ts#L40

The formatting of the innermost error lead me to think it's actually failing here 

https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/http-client/src/index.ts#L535

What I'm not sure about is why would the time out occur before 3 minutes since:
- [no options are passed when initializing the client])https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/artifact/src/internal/download/download-artifact.ts#L41_
- [the default value for the timeout is undefined](https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/http-client/src/index.ts#L158)
- (a hardcoded safeguard of 3 minutes is in place)

It almost seems like the service storing the artifacts is disconnecting this client for some reason (partition getting hot? network congestion?... something else?) It might be caused because the server sends back a 408 and 408's are not being retried in the current setup.

https://github.com/actions/toolkit/blob/68f22927e727a60caff909aaaec1ab7267b39f75/packages/http-client/src/index.ts#L69

But this is hard to confirm without more detailed logs/access to telemetry.

I think it'd be beneficial if some of you could:
1. Open an issue on the upstream repo to call for attention (actions/toolkit) on this issue.
2. Cross-check my analysis and add some additional pointers to it.

(I've also reached out privately to some GitHub employees)

**Comment by andrewakim** [comment]
:wave: Hi all - Thanks for reporting this issue. I just wanted to let ya'll know we're investigating it now and I'll try to post an update when we learn more.

**Comment by jcarranzan** [comment]
From my side it worked renaming the name in the jobs yamls, as mentioned in https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md 
Before it was `    name: my-artifact `
Now it is  `       name: my-artifact-${{ matrix.runs-on }}`

**Comment by garysassano** [comment]
I'm experiencing the same issue.

**Comment by EnricoMi** [comment]
> From my side it worked renaming the name in the jobs yamls

@jcarranzan Artifacts with identical names case the following error:

    Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

That is unrelated to the "Request timeout" reported here. You may have seen both issues at the same time, still unrelated.

**Comment by jcarranzan** [comment]
> > From my side it worked renaming the name in the jobs yamls
> 
> @jcarranzan Artifacts with identical names case the following error:
> 
> ```
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
> ```
> 
> That is unrelated to the "Request timeout" reported here. You may have seen both issues at the same time, still unrelated.

Ok, it could be unrelated but the original error post : 
`Unable to download artifact(s): Unable to download and extract artifact: Request timeout: /actions-results/48835bcc-3d9d-48c1-9b25-e61724c412e6/workflow-job-run-133fda40-ba8c-5571-226b-e94c9a723dbe/artifacts/scipy-notebook-x86_64.zip?se=2023-12-14T22%3A41%3A57Z&sig=kIu7CPVgJ9myrpzJC9NS%2FLVc8z8fcQtdDXC0sDa5DVc%3D&sp=r&spr=https&sr=b&st=2023-12-14T22%3A31%3A57Z&sv=2021-12-02`.
It was almost the same error with different repo (obviously) that I got before renaming some of our identical names use in the yamls configuration, for instance  in my case I change` ci-artifacts`by the specific name  `artifacts-latest-linux-native${{ matrix.java }}.
Anyways, thanks for your comment @EnricoMi

**Comment by cpcloud** [comment]
We see this quite frequently over in the Ibis project. Here's an example run: https://github.com/actions/download-artifact/issues/249

**Comment by jamezp** [comment]
I'm starting to see this fail with V3 now https://github.com/wildfly/wildfly-arquillian/actions/runs/7269487118/job/19838968251

**Comment by EnricoMi** [comment]
> I'm starting to see this fail with V3 now https://github.com/wildfly/wildfly-arquillian/actions/runs/7269487118/job/19838968251

You are uploading with `@v4` and downloading with `@v3`, which might not be supported.

**Comment by patrick-stephens** [comment]
I'm seeing intermittent failures in a matrix job each downloading (with v4) the same artefact (uploaded previously with v4) - the workflow is identical and using the same artefact but fails for different matrix jobs on different runs. It does seem to be some kind of flakiness - rerunning can resolve it or trigger a different one of the matrix jobs to fail.

**Comment by dannyskoog** [comment]
Experiencing exactly the same @patrick-stephens

**Comment by rokibhasansagar** [comment]
Facing somewhat similar problem.
I uploaded artifact with v4, then when try to download with v4 in a matrix job, a few somehow gets timeout error, yet the step does not return error code 1. So, it's *Always* successful no matter the artifact is downloaded or timed-out.
If it is Not downloaded, at least return a error code so that next step can pick up on that error and run some extra conditional step to mitigate it (like a retry of the same step when and if needed).
Or simply, when got a timeout, just add a back-off timeout and retry internally through the action itself. That would be most helpful for users.

**Comment by remal** [comment]
I have this issue very frequently after updating to v4 (both action/upload-artifact and action/download-artifact)

**Comment by tanimaroy2012** [comment]
yeah im facing this issue with v4 and v4.1.0

**Comment by GuyAfik** [comment]
Having the same problem as everyone else describes, downgrading to v3 solves the issue.

**Comment by sue445** [comment]
My workaround is following

**Before**
```yaml
- name: Download all artifacts
  uses: actions/download-artifact@v4
  with:
    path: bin/
    pattern: bin-*
    merge-multiple: true
```

**After**
```yaml
# FIXME: Workaround for https://github.com/actions/download-artifact/issues/249
- name: Download all artifacts with retry
  uses: Wandalen/wretry.action@master
  with:
    action: actions/download-artifact@v4
    with: |
      path: bin/
      pattern: bin-*
      merge-multiple: true
    attempt_limit: 5
    attempt_delay: 1000
```

I have had this workaround in my repository for about 2 weeks now and I have not seen a single timeout error.

**Comment by nedbat** [comment]
@andrewakim @robherley You were helpful with the upload issues in https://github.com/actions/upload-artifact/issues/472, can you help here?  Should we all be adding explicit retry options to keep our downloads working?  I can confirm that I have seen these timeouts since switching to v4 and had not before.

**Comment by mikesprague** [comment]
> @andrewakim @robherley You were helpful with the upload issues in [actions/upload-artifact#472](https://github.com/actions/upload-artifact/issues/472), can you help here? Should we all be adding explicit retry options to keep our downloads working? I can confirm that I have seen these timeouts since switching to v4 and had not before.

Based on this warning after trying `attempt_limit` and `attempt_retry`, I might suggest _NOT_ using them:

```shell
Unexpected input(s) 'attempt_limit', 'attempt_delay', valid inputs are ['name', 'path', 'pattern', 'merge-multiple', 'github-token', 'repository', 'run-id']
```

**Comment by EnricoMi** [comment]
> Based on this warning after trying `attempt_limit` and `attempt_retry`, I might suggest _NOT_ using them:

Looking closely at https://github.com/actions/download-artifact/issues/249#issuecomment-1873749814 you can see that @sue445 is using a different action (that has inputs `attempt_limit` and `attempt_retry`), that executes and retries the action `download-artifact`.

**Comment by mikesprague** [comment]
> > Based on this warning after trying `attempt_limit` and `attempt_retry`, I might suggest _NOT_ using them:
> 
> Looking closely at [#249 (comment)](https://github.com/actions/download-artifact/issues/249#issuecomment-1873749814) you can see that @sue445 is using a different action (that has inputs `attempt_limit` and `attempt_retry`), that executes and retries the action `download-artifact`.

Yep. Edited my comment noting that moments after posting it. Thanks!

**Comment by webknjaz** [comment]
> It almost seems like the service storing the artifacts is disconnecting this client for some reason (partition getting hot? network congestion?... something else?) It might be caused because the server sends back a 408 and 408's are not being retried in the current setup.

I was suggesting a fix for something similar in https://github.com/actions/toolkit/issues/1235.

@baywet does that sound related?

**Comment by jonkoops** [comment]
Please do not comment on this thread confirming the issue, as that adds nothing to the discussion aside from more noise. If you are experiencing this problem, use the :+1: reaction on the issue to 'upvote' instead.

**Comment by Santas** [comment]
Shouldn't this be marked on GithubStatus as downgraded performance?

**Comment by perfectmak** [comment]
I'm getting a similar but slightly different errors:
```
Unable to download artifact(s): Unable to download and extract artifact: Unexpected HTTP response from blob storage: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

Is this related to this issue and will this be fixed with the fixes?

**Comment by mhemmings** [comment]
@vmjoseph I'm not sure this should be marked as closed, given the "fix" is a bit of a patch/temporary solution masking an underlying issue?

**Comment by jeroen** [comment]
This is still flaky, after bumping to v4 getting lots of failures again: https://github.com/r-universe/tiledb-inc/actions/runs/7978856468/job/21785898976

**Comment by Garett-MacGowan** [comment]
> This is still flaky, after bumping to v4 getting lots of failures again: https://github.com/r-universe/tiledb-inc/actions/runs/7978856468/job/21785898976

I noticed that your failure is not related to a timeout.

Can someone confirm whether the timeout issue is fixed?

**Comment by dannyskoog** [comment]
> > This is still flaky, after bumping to v4 getting lots of failures again: https://github.com/r-universe/tiledb-inc/actions/runs/7978856468/job/21785898976
> 
> 
> 
> I noticed that your failure is not related to a timeout.
> 
> 
> 
> Can someone confirm whether the timeout issue is fixed?

Since the fix was released ~3 months ago I haven't faced the timeout issue again, using v4. Also, the lack of activity in here implies that it was indeed fixed across the board IMHO

**Comment by rwader-swi** [comment]
I'm still getting the timeout after 5 retries error on v4. I'm using v4 of both upload-artifacts and download-artifacts.
So I switched download-artifacts to v4.0.0, and apparently the download works (but too slow), but I don't think the download is getting completed, because while untar-ing the file I get _unexpected end of file error._ So v4.0.0 is masking incomplete downloading error.
Somebody please let me know which other version should I try. I'm stuck 😢😭

**Comment by rwader-swi** [comment]
Also I've observed this download gets completed within 1 min on github runners, while on self-hosted it takes >1 hour.

**Comment by rwader-swi** [comment]
> I'm still getting the timeout after 5 retries error on v4. I'm using v4 of both upload-artifacts and download-artifacts. So I switched download-artifacts to v4.0.0, and apparently the download works (but too slow), but I don't think the download is getting completed, because while untar-ing the file I get _unexpected end of archive error._ So v4.0.0 is masking incomplete downloading error. Although this all is working quick and correctly on non-self-hosted github runners Somebody please let me know which other version should I try. I'm stuck 😢😭

I changed tar to tar.gz and used **v3** of both actions and its working. That too in 30% less time
